### ISSUE TITLE
Workflows fail while trying to send reports to DefectDojo

### ISSUE THREAD

**Issue by babisRoutis** [eu-digital-identity-wallet/eudi-infra-ci#4]
All flows that include sending a report to DefectDojo are failing.

- [ ] `sast_action`
- [ ] `sast_bt`
- [ ] `sast_bt_no_cov`
- [ ] `sca`
- [ ] `sca_bt`
- [ ] `secretscanning`

**Comment by babisRoutis** [comment]
@christosservosNCIN Can you please update the status of this issue?

**Comment by christosservosNCIN** [comment]
Hello,

this step was indeed failing. The cause was related to a configuration error. It has now been resolved and the "posting to Dojo" step is now re-enabled and working as intended.

Regards,
